// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag

package docs

import (
	"bytes"
	"encoding/json"
	"strings"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "license": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/v1/mailTemplates": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "mailTemplate"
                ],
                "summary": "Creates mail templates",
                "parameters": [
                    {
                        "description": "Mail template information",
                        "name": "mailTemplate",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.MailTemplateForm"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/gin.H"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/gin.H"
                        }
                    }
                }
            }
        },
        "/v1/needies": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "needy"
                ],
                "summary": "Lists all needies",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/gin.H"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/gin.H"
                        }
                    }
                }
            },
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "needy"
                ],
                "summary": "Creates needy",
                "parameters": [
                    {
                        "description": "Needy information",
                        "name": "needy",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.NeedyForm"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/gin.H"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/gin.H"
                        }
                    }
                }
            }
        },
        "/v1/needies/informations": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "needy"
                ],
                "summary": "Lists all needies informations",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/gin.H"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/gin.H"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "controllers.MailTemplateForm": {
            "type": "object",
            "properties": {
                "mailTemplateType": {
                    "type": "integer"
                },
                "template": {
                    "type": "string"
                }
            }
        },
        "controllers.NeedyForm": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "object",
                    "$ref": "#/definitions/models.Address"
                },
                "firstName": {
                    "type": "string"
                },
                "lastName": {
                    "type": "string"
                },
                "needs": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Need"
                    }
                },
                "needyCategories": {
                    "type": "integer"
                },
                "phoneNumber": {
                    "type": "string"
                },
                "priority": {
                    "type": "integer"
                },
                "summary": {
                    "type": "string"
                }
            }
        },
        "gin.H": {
            "type": "object",
            "additionalProperties": true
        },
        "models.Address": {
            "type": "object",
            "properties": {
                "city": {
                    "type": "string"
                },
                "district": {
                    "type": "string"
                },
                "firstLine": {
                    "type": "string"
                },
                "firstName": {
                    "type": "string"
                },
                "lastName": {
                    "type": "string"
                },
                "phoneNumber": {
                    "type": "string"
                },
                "postalCode": {
                    "type": "string"
                },
                "secondLine": {
                    "type": "string"
                }
            }
        },
        "models.Good": {
            "type": "object",
            "properties": {
                "goodCategory": {
                    "type": "integer"
                },
                "isAvailable": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "photoLink": {
                    "type": "string"
                },
                "price": {
                    "type": "number"
                }
            }
        },
        "models.LineItem": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "integer"
                },
                "description": {
                    "type": "string"
                },
                "good": {
                    "type": "object",
                    "$ref": "#/definitions/models.Good"
                }
            }
        },
        "models.Need": {
            "type": "object",
            "properties": {
                "cancelledAt": {
                    "type": "string"
                },
                "cancelledBy": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "fulfilledAt": {
                    "type": "string"
                },
                "fulfilledBy": {
                    "description": "TODO: change this",
                    "type": "string"
                },
                "isCancelled": {
                    "type": "boolean"
                },
                "isFulfilled": {
                    "type": "boolean"
                },
                "lineItems": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.LineItem"
                    }
                },
                "name": {
                    "type": "string"
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "",
	Host:        "",
	BasePath:    "",
	Schemes:     []string{},
	Title:       "",
	Description: "",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
