definitions:
  controllers.LineItemForm:
    properties:
      amount:
        type: integer
      description:
        type: string
      good:
        $ref: '#/definitions/models.Good'
        type: object
    type: object
  controllers.MailTemplateForm:
    properties:
      mailTemplateType:
        type: integer
      template:
        type: string
    type: object
  controllers.NeedForm:
    properties:
      description:
        type: string
      lineItems:
        items:
          $ref: '#/definitions/controllers.LineItemForm'
        type: array
      name:
        type: string
      priority:
        type: integer
    type: object
  controllers.NeedyForm:
    properties:
      address:
        $ref: '#/definitions/models.Address'
        type: object
      firstName:
        type: string
      lastName:
        type: string
      needyCategories:
        items:
          type: integer
        type: array
      phoneNumber:
        type: string
      priority:
        type: integer
      summary:
        type: string
    type: object
  controllers.PaymentForm:
    properties:
      creditCardNumber:
        type: string
      cvv:
        type: string
      expireDate:
        type: string
      fullName:
        type: string
    type: object
  gin.H:
    additionalProperties: true
    type: object
  models.Address:
    properties:
      city:
        type: string
      district:
        type: string
      firstLine:
        type: string
      firstName:
        type: string
      lastName:
        type: string
      phoneNumber:
        type: string
      postalCode:
        type: string
      secondLine:
        type: string
    type: object
  models.Good:
    properties:
      goodId:
        description: "Name         string             `bson:\"name\" json:\"name\"`\n\tPrice        float32            `bson:\"price\" json:\"price\"`\n\tPhotoLink    string             `bson:\"photoLink\" json:\"photoLink\"`\n\tIsAvailable  bool               `bson:\"isAvailable\" json:\"isAvailable\"`\n\tGoodCategory enums.GoodCategory `bson:\"goodCategory\" json:\"goodCategory\"`"
        type: integer
    type: object
info:
  contact: {}
  license: {}
paths:
  /v1/mailTemplates:
    post:
      parameters:
      - description: Mail template information
        in: body
        name: mailTemplate
        required: true
        schema:
          $ref: '#/definitions/controllers.MailTemplateForm'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/gin.H'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/gin.H'
      summary: Creates mail templates
      tags:
      - mailTemplate
  /v1/needies:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/gin.H'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/gin.H'
      summary: Lists all needies
      tags:
      - needy
    post:
      parameters:
      - description: Needy information
        in: body
        name: needy
        required: true
        schema:
          $ref: '#/definitions/controllers.NeedyForm'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/gin.H'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/gin.H'
      summary: Creates needy
      tags:
      - needy
  /v1/needies/{id}/addNeed:
    post:
      parameters:
      - description: ID
        in: path
        name: id
        required: true
        type: string
      - description: Need information
        in: body
        name: needy
        required: true
        schema:
          $ref: '#/definitions/controllers.NeedForm'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/gin.H'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/gin.H'
      summary: Add need to needy
      tags:
      - needy
  /v1/needies/getNeedyDetail/{id}:
    get:
      parameters:
      - description: ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/gin.H'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/gin.H'
      summary: Get needy detail
      tags:
      - needy
  /v1/needies/informations:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/gin.H'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/gin.H'
      summary: Lists all needies informations
      tags:
      - needy
  /v1/needs:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/gin.H'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/gin.H'
      summary: Lists all needs
      tags:
      - need
  /v1/needs/{needId}/cancel:
    delete:
      parameters:
      - description: ID
        in: path
        name: needId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/gin.H'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/gin.H'
      summary: Cancels need
      tags:
      - need
  /v1/needs/{needId}/setFulfilled:
    get:
      parameters:
      - description: ID
        in: path
        name: needId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/gin.H'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/gin.H'
      summary: Set need as fulfilled
      tags:
      - need
  /v1/payment/{needId}:
    post:
      parameters:
      - description: ID
        in: path
        name: needId
        required: true
        type: string
      - description: Payment information
        in: body
        name: payment
        required: true
        schema:
          $ref: '#/definitions/controllers.PaymentForm'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/gin.H'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/gin.H'
      summary: Pay need
      tags:
      - need
swagger: "2.0"
